// Lista de personajes (sin duplicados) y utilidades para select

export const CHARACTER_LIST: string[] = [
  'Rem',
  'Emilia',
  'Megumin',
  'Asuna Yuuki',
  'Zero Two',
  'Aqua',
  'Kurisu Makise',
  'Tohru',
  'Tsuyu Asui',
  'Ochaco Uraraka',
  'Lalatina Ford Dustiness',
  'Mai Sakurajima',
  'Rin Tohsaka',
  'Shinobu Oshino',
  'Artoria Pendragon',
  'Ai Hayasaka',
  'Kanna Kamui',
  'Yor Forger',
  'Nezuko Kamado',
  'Shinobu Kocho',
  'Maki Zenin',
  'Makima',
  'Hinata Hyuga',
  'Yumeko Jabami',
  'Mitsuri Kanroji',
  'Nami',
  'Bulma Briefs',
  'Touka Kirishima',
  'Violet Evergarden',
  'Tsunade Senju',
  'Faye Valentine',
  'Revy',
  'Albedo',
  'Kiss Shot',
  'Akeno Himejima',
  'Rias Gremory',
  'Fubuki',
  'Yoruichi Shihoin',
  'Boa Hancock',
  'Mei Mei',
  'Merlin',
  'Azusa Hamaoka',
  'Tsubasa Hanekawa',
  'Momo Ayase',
  'Frieren',
  'Kana Arima',
  'Himiko Toga',
  'Senjumaru Shutara',
  'Mina Ashiro',
  'Turbo Granny',
  'Akane Tendo',
  'Mikasa Ackerman',
  'Rukia Kuchiki',
  'Hestia',
  'Kurumi Tokisaki',
  'Kaguya Shinomiya',
  'Marin Kitagawa',
  'Miyo Saimori',
  'Fuyutsuki',
  'Erza Scarlet',
  'Raphtalia',
  'Nobara Kugisaki',
  'Annie Leonhart',
  'Shion Karanomari',
  'Anna Yamada',
  'Maomao',
  'Momo Belia Deviluke',
  'Sagiri Izumi',
  'Beatrice',
  'Nico Robin',
  'Akame',
  'Kiryuuin Satsuki',
  'Seiko Ayase',
  'Stocking Anarchy',
  'Beatrix Amerhauser',
  'Android 18',
  'Mirko',
  'Shura Kirigakure',
]

// Sugerencia de estructura para selects (centrado solo en este archivo)
export type SelectOption = { value: string; label: string }

export const CHARACTER_OPTIONS: SelectOption[] = CHARACTER_LIST.map((name) => ({
  value: name,
  label: name,
}))